/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kissdry.jsonviewer.ui;

import java.awt.Toolkit;

/**
 *
 * @author Administrator
 */
public class JSONViewerAboutBoxJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainAboutBox
     */
    public JSONViewerAboutBoxJFrame() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(
                getClass().getClassLoader().getResource("resources/images/json3.png")));//这个不能以 '/'开头]
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        versionLabel = new javax.swing.JLabel();
        versionValue = new javax.swing.JLabel();
        titleValue = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        authorValue = new javax.swing.JLabel();
        contactValue = new javax.swing.JLabel();
        websiteLabel = new javax.swing.JLabel();
        websiteValue = new javax.swing.JLabel();
        descValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        versionLabel.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        versionLabel.setText(JSONViewerUIUtil.getI18nById("versionLabel"));
        versionLabel.setFocusable(false);
        versionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        versionValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        versionValue.setText(JSONViewerUIUtil.getI18nById("versionValue"));
        versionValue.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        titleValue.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        titleValue.setText(JSONViewerUIUtil.getI18nById("titleValue"));

        authorLabel.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        authorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        authorLabel.setText(JSONViewerUIUtil.getI18nById("authorLabel"));
        authorLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        contactLabel.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        contactLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        contactLabel.setText(JSONViewerUIUtil.getI18nById("contactLabel"));
        contactLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        authorValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        authorValue.setText(JSONViewerUIUtil.getI18nById("authorValue"));
        authorValue.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        contactValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contactValue.setText(JSONViewerUIUtil.getI18nById("contactValue"));
        contactValue.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        websiteLabel.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        websiteLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        websiteLabel.setText(JSONViewerUIUtil.getI18nById("websiteLabel"));
        websiteLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        websiteValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        websiteValue.setText(JSONViewerUIUtil.getI18nById("websiteValue"));
        websiteValue.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        descValue.setFont(new java.awt.Font("宋体", 2, 14)); // NOI18N
        descValue.setText(JSONViewerUIUtil.getI18nById("descValue"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(contactValue, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(authorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(authorValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(versionValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(titleValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(websiteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(websiteValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(descValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(titleValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descValue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionLabel)
                    .addComponent(versionValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorLabel)
                    .addComponent(authorValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel)
                    .addComponent(contactValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(websiteLabel)
                    .addComponent(websiteValue))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JSONViewerAboutBoxJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JSONViewerAboutBoxJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JSONViewerAboutBoxJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JSONViewerAboutBoxJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JSONViewerAboutBoxJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel authorValue;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel contactValue;
    private javax.swing.JLabel descValue;
    private javax.swing.JLabel titleValue;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JLabel versionValue;
    private javax.swing.JLabel websiteLabel;
    private javax.swing.JLabel websiteValue;
    // End of variables declaration//GEN-END:variables
}
