/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kissdry.ui;

/**
 *
 * @author Administrator
 */
public class JSONViewerAboutBoxJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainAboutBox
     */
    public JSONViewerAboutBoxJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        versionLabel = new javax.swing.JLabel();
        versionValue = new javax.swing.JLabel();
        titleValue = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        authorValue = new javax.swing.JLabel();
        contactValue = new javax.swing.JLabel();
        websiteLabel = new javax.swing.JLabel();
        websiteValue = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        descValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        versionLabel.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        versionLabel.setText(JSONViewerUIUtil.getI18nById("versionLabel"));

        versionValue.setText(JSONViewerUIUtil.getI18nById("versionValue"));

        titleValue.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        titleValue.setText(JSONViewerUIUtil.getI18nById("titleValue"));

        authorLabel.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        authorLabel.setText(JSONViewerUIUtil.getI18nById("authorLabel"));

        contactLabel.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        contactLabel.setText(JSONViewerUIUtil.getI18nById("contactLabel"));

        authorValue.setText(JSONViewerUIUtil.getI18nById("authorValue"));

        contactValue.setText(JSONViewerUIUtil.getI18nById("contactValue"));

        websiteLabel.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        websiteLabel.setText(JSONViewerUIUtil.getI18nById("websiteLabel"));

        websiteValue.setText(JSONViewerUIUtil.getI18nById("websiteValue"));

        closeButton.setText(JSONViewerUIUtil.getI18nById("closeButton"));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        descValue.setFont(new java.awt.Font("宋体", 2, 14)); // NOI18N
        descValue.setText(JSONViewerUIUtil.getI18nById("descValue"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(contactLabel)
                                .addGap(18, 18, 18)
                                .addComponent(contactValue, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(authorLabel)
                                .addGap(18, 18, 18)
                                .addComponent(authorValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(versionLabel)
                                .addGap(18, 18, 18)
                                .addComponent(versionValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(titleValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(websiteLabel)
                                .addGap(18, 18, 18)
                                .addComponent(websiteValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(descValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(titleValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descValue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionLabel)
                    .addComponent(versionValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorLabel)
                    .addComponent(authorValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel)
                    .addComponent(contactValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(websiteLabel)
                    .addComponent(websiteValue))
                .addGap(27, 27, 27)
                .addComponent(closeButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
        ControllerJFrame.showMainJFrame();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JSONViewerAboutBoxJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JSONViewerAboutBoxJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JSONViewerAboutBoxJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JSONViewerAboutBoxJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JSONViewerAboutBoxJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel authorValue;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel contactValue;
    private javax.swing.JLabel descValue;
    private javax.swing.JLabel titleValue;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JLabel versionValue;
    private javax.swing.JLabel websiteLabel;
    private javax.swing.JLabel websiteValue;
    // End of variables declaration//GEN-END:variables
}
